---
title: "My dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

knitr::opts_chunk$set(
 	echo = TRUE,
 	warning = FALSE,
 	fig.width = 8, 
   fig.height = 6,
   out.width = "90%"
 )

options(
   ggplot2.continuous.colour = "viridis",
   ggplot2.continuous.fill = "viridis"
 )

 scale_colour_discrete = scale_colour_viridis_d
 scale_fill_discrete = scale_fill_viridis_d

 theme_set(theme_minimal() + theme(legend.position = "bottom"))
 
set.seed(1)

data("rest_inspec")

rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C", "Not Yet Graded"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>% 
  group_by(cuisine_description, boro) %>% 
  count(cuisine_description, sort = TRUE) %>% 
  plot_ly(x = ~ cuisine_description, y = ~n, color = ~ boro, type = "bar") %>% 
    layout(
    title = "Total Count Of Top 15 Most Popular Cuisines By Boro")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
density = 
  rest_inspec %>% 
  filter(str_detect(cuisine_description, regex ("kosher", ignore_case = TRUE))) %>% 
  ggplot(aes(x = boro, fill = grade)) +
  geom_density(alpha = .5) +
  labs (
    title = "Distribution Of Grades For Kosher Restaurants Among Boros ",
    x = "Boro",
    y = "Density",
    caption = "Data from nyc.gov"
  )

ggplotly(density)
```

### Chart C

```{r}
grade_over_t = 
  rest_inspec %>% 
  group_by(grade) %>% 
  filter(
    str_detect(dba, regex("tequil", ignore_case = TRUE))) %>% 
  ggplot(aes(x = inspection_date, y = grade, color = dba, group = dba))+
  geom_point() + geom_line() +
  labs (
    title = "Grades Over Time For Tequila Bars",
    x = "Year",
    y = "Grade",
    caption = "Data from nyc.gov"
  )

ggplotly(grade_over_t)
```

